air_boltic_analytics:
  target: dev
  outputs:
    dev:
      type: databricks
      method: http
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH').replace('SQL:','') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      catalog: dev
      schema: "{{ env_var('USER','developer') }}"
      threads: "{{ env_var('DBT_THREADS', 8) | int }}"
    ci:
      type: databricks
      method: http
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH').replace('SQL:','') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      catalog: "{{ env_var('DBT_ENV_SECRET_DATABRICKS_CATALOG','dev') }}"
      schema: "{{ env_var('DBT_ENV_SECRET_CI_SCHEMA') }}"
      threads: "{{ env_var('DBT_THREADS', 8) | int }}"
    stg:
      type: databricks
      method: http
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH').replace('SQL:','') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      catalog: stg
      schema: analytics
      threads: "{{ env_var('DBT_THREADS', 8) | int }}"
    prod:
      type: databricks
      method: http
      host: "{{ env_var('DATABRICKS_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_HTTP_PATH').replace('SQL:','') }}"
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      catalog: air_boltic
      schema: analytics
      threads: "{{ env_var('DBT_THREADS', 8) | int }}"
